import type { RarityCategory, Theme, Tile } from "@/domain/types";
import { rarityScoreFor } from "@/domain/rarity";

/**
 * Dog Spotting theme content. Rarity is editorially assigned (§9).
 * Artwork is placeholder (emoji + swatch in metadata) until Milestone 5
 * produces approved illustrations.
 */

type Seed = {
  slug: string;
  name: string;
  short?: string;
  category:
    | "breed"
    | "mixed_breed"
    | "behavior"
    | "clothing"
    | "owner_interaction"
    | "environment"
    | "special";
  rarity: RarityCategory;
  emoji: string;
  hue: number;
  tips: string;
  size?: string;
  coat?: string;
  description?: string;
};

const THEME_ID = "theme_dog";

const SEEDS: Seed[] = [
  // ---------- Breeds ----------
  {
    slug: "golden_retriever",
    name: "Golden Retriever",
    category: "breed",
    rarity: "common",
    emoji: "🦮",
    hue: 40,
    tips: "Feathered golden coat, broad friendly head, thick feathered tail carried level.",
    size: "Large (55–75 lb)",
    coat: "Medium-long, golden to cream",
  },
  {
    slug: "labrador",
    name: "Labrador Retriever",
    short: "Labrador",
    category: "breed",
    rarity: "common",
    emoji: "🐕",
    hue: 30,
    tips: "Short dense coat in yellow, black, or chocolate; thick 'otter' tail; broad head.",
    size: "Large (55–80 lb)",
    coat: "Short, dense, water-resistant",
  },
  {
    slug: "french_bulldog",
    name: "French Bulldog",
    short: "Frenchie",
    category: "breed",
    rarity: "common",
    emoji: "🐶",
    hue: 200,
    tips: "Compact muscular body, very short muzzle, large upright bat ears.",
    size: "Small (under 28 lb)",
    coat: "Short and smooth",
  },
  {
    slug: "poodle",
    name: "Poodle",
    category: "breed",
    rarity: "common",
    emoji: "🐩",
    hue: 320,
    tips: "Tight curly coat, long narrow muzzle, often clipped; comes in toy, mini, and standard sizes.",
    size: "Toy to large",
    coat: "Dense curls, single color",
  },
  {
    slug: "chihuahua",
    name: "Chihuahua",
    category: "breed",
    rarity: "common",
    emoji: "🐕",
    hue: 20,
    tips: "Tiny; apple-shaped head, large erect ears, prominent eyes.",
    size: "Tiny (2–6 lb)",
    coat: "Smooth or long",
  },
  {
    slug: "dachshund",
    name: "Dachshund",
    short: "Dachshund",
    category: "breed",
    rarity: "common",
    emoji: "🌭",
    hue: 25,
    tips: "Very long body on very short legs; long drooping ears.",
    size: "Small, long",
    coat: "Smooth, wire, or long",
  },
  {
    slug: "beagle",
    name: "Beagle",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 35,
    tips: "Tricolor (black/tan/white), long soft ears, white-tipped tail held high.",
    size: "Small-medium (20–30 lb)",
    coat: "Short, tricolor",
  },
  {
    slug: "husky",
    name: "Siberian Husky",
    short: "Husky",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐺",
    hue: 210,
    tips: "Wolf-like face mask, erect triangular ears, thick coat, often blue eyes, curled bushy tail.",
    size: "Medium-large (35–60 lb)",
    coat: "Thick double coat, grey/black & white",
  },
  {
    slug: "german_shepherd",
    name: "German Shepherd",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕‍🦺",
    hue: 30,
    tips: "Black-and-tan, large erect ears, sloping back, bushy tail carried low.",
    size: "Large (50–90 lb)",
    coat: "Medium double coat",
  },
  {
    slug: "pug",
    name: "Pug",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐶",
    hue: 45,
    tips: "Round wrinkled face, flat muzzle, black mask on fawn coat, tightly curled tail.",
    size: "Small (14–18 lb)",
    coat: "Short, fawn or black",
  },
  {
    slug: "corgi",
    name: "Corgi",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 35,
    tips: "Long low body, big upright ears, fox-like face, fluffy rear.",
    size: "Small-medium, long and low",
    coat: "Medium, red/sable/tri with white",
  },
  {
    slug: "shih_tzu",
    name: "Shih Tzu",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 300,
    tips: "Small with long flowing or puppy-clipped coat, short muzzle, often a topknot.",
    size: "Small (9–16 lb)",
    coat: "Long, silky, many colors",
  },
  {
    slug: "border_collie",
    name: "Border Collie",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 220,
    tips: "Black and white, intense stare, medium coat, athletic build, semi-erect ears.",
    size: "Medium (30–45 lb)",
    coat: "Medium, black & white",
  },
  {
    slug: "boxer",
    name: "Boxer",
    category: "breed",
    rarity: "uncommon",
    emoji: "🥊",
    hue: 25,
    tips: "Square muscular build, short blunt muzzle with underbite, fawn or brindle with white chest.",
    size: "Medium-large (50–70 lb)",
    coat: "Short, fawn/brindle",
  },
  {
    slug: "australian_shepherd",
    name: "Australian Shepherd",
    short: "Aussie",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 260,
    tips: "Merle or tricolor coat, medium length, often bobbed tail and blue/odd eyes.",
    size: "Medium (40–65 lb)",
    coat: "Medium, merle/tri",
  },
  {
    slug: "yorkie",
    name: "Yorkshire Terrier",
    short: "Yorkie",
    category: "breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 210,
    tips: "Tiny with long silky steel-blue and tan coat, small erect ears, often a bow.",
    size: "Tiny (under 7 lb)",
    coat: "Long, silky, blue & tan",
  },
  {
    slug: "great_dane",
    name: "Great Dane",
    category: "breed",
    rarity: "rare",
    emoji: "🐕",
    hue: 0,
    tips: "Enormous but sleek; long head, floppy or cropped ears, deep chest.",
    size: "Giant (110–175 lb)",
    coat: "Short; fawn, brindle, harlequin, black, blue",
  },
  {
    slug: "bernese",
    name: "Bernese Mountain Dog",
    short: "Bernese",
    category: "breed",
    rarity: "rare",
    emoji: "🐕",
    hue: 15,
    tips: "Large, tricolor with white blaze and chest, rust points, long thick coat.",
    size: "Large (70–115 lb)",
    coat: "Long, tricolor",
  },
  {
    slug: "dalmatian",
    name: "Dalmatian",
    category: "breed",
    rarity: "rare",
    emoji: "🐕",
    hue: 0,
    tips: "White with distinct black or liver spots; athletic; long tapering tail.",
    size: "Medium-large (45–70 lb)",
    coat: "Short, spotted",
  },
  {
    slug: "greyhound",
    name: "Greyhound / Whippet",
    short: "Greyhound",
    category: "breed",
    rarity: "rare",
    emoji: "🐕",
    hue: 180,
    tips: "Very slim, deep chest, tucked waist, long narrow head, rose ears.",
    size: "Medium-large, very lean",
    coat: "Very short",
  },
  {
    slug: "basset_hound",
    name: "Basset Hound",
    short: "Basset",
    category: "breed",
    rarity: "rare",
    emoji: "🐕",
    hue: 30,
    tips: "Very long ears touching the ground, droopy eyes and jowls, heavy low body.",
    size: "Medium, very low",
    coat: "Short, tricolor or bicolor",
  },
  {
    slug: "saint_bernard",
    name: "Saint Bernard",
    category: "breed",
    rarity: "rare",
    emoji: "🐕",
    hue: 20,
    tips: "Massive, red/brown and white with dark mask, heavy jowls.",
    size: "Giant (120–180 lb)",
    coat: "Short or long, red & white",
  },

  // ---------- Mixed / type ----------
  {
    slug: "doodle",
    name: "Doodle-type Dog",
    short: "Doodle",
    category: "mixed_breed",
    rarity: "common",
    emoji: "🧸",
    hue: 40,
    tips: "Shaggy wavy or curly teddy-bear coat, poodle-like face with a softer muzzle (Goldendoodle, Labradoodle, etc.).",
    size: "Medium to large",
    coat: "Wavy/curly, often apricot or cream",
  },
  {
    slug: "terrier_mix",
    name: "Scruffy Terrier Mix",
    short: "Terrier Mix",
    category: "mixed_breed",
    rarity: "common",
    emoji: "🐕",
    hue: 50,
    tips: "Small-to-medium, wiry scruffy coat, beard, alert expression.",
    size: "Small-medium",
    coat: "Wiry, scruffy",
  },
  {
    slug: "shepherd_mix",
    name: "Shepherd Mix",
    category: "mixed_breed",
    rarity: "uncommon",
    emoji: "🐕",
    hue: 35,
    tips: "Medium-large, upright or semi-erect ears, tan/black coloring, shepherd-ish face.",
    size: "Medium-large",
    coat: "Medium",
  },
  {
    slug: "pit_type",
    name: "Pit Bull-type Dog",
    short: "Pittie",
    category: "mixed_breed",
    rarity: "common",
    emoji: "🐕",
    hue: 15,
    tips: "Muscular, broad head and cheeks, short coat, wide smile.",
    size: "Medium (35–65 lb)",
    coat: "Short, any color",
  },

  // ---------- Behavior ----------
  {
    slug: "dog_playing_fetch",
    name: "Dog Playing Fetch",
    short: "Fetch",
    category: "behavior",
    rarity: "common",
    emoji: "🎾",
    hue: 90,
    tips: "Any dog chasing or returning a thrown ball, stick, or frisbee.",
  },
  {
    slug: "dog_carrying_toy",
    name: "Dog Carrying a Toy",
    short: "Carrying Toy",
    category: "behavior",
    rarity: "common",
    emoji: "🧸",
    hue: 340,
    tips: "Walking with a toy, ball, or stick in its mouth.",
  },
  {
    slug: "two_dogs_playing",
    name: "Two Dogs Playing",
    category: "behavior",
    rarity: "common",
    emoji: "🐕🐕",
    hue: 120,
    tips: "Two dogs wrestling, chasing, or play-bowing together.",
  },
  {
    slug: "dog_sniffing",
    name: "Dog Sniffing Intently",
    short: "Sniffing",
    category: "behavior",
    rarity: "common",
    emoji: "👃",
    hue: 60,
    tips: "Nose down, fully absorbed in a smell.",
  },
  {
    slug: "dog_barking",
    name: "Dog Barking",
    short: "Barking",
    category: "behavior",
    rarity: "common",
    emoji: "📣",
    hue: 10,
    tips: "You must hear it bark.",
  },
  {
    slug: "dog_digging",
    name: "Dog Digging",
    short: "Digging",
    category: "behavior",
    rarity: "uncommon",
    emoji: "🕳️",
    hue: 30,
    tips: "Actively digging in dirt, sand, or snow.",
  },
  {
    slug: "dog_swimming",
    name: "Dog Swimming",
    short: "Swimming",
    category: "behavior",
    rarity: "rare",
    emoji: "🏊",
    hue: 200,
    tips: "In water, actually paddling (not just wading).",
  },
  {
    slug: "dog_rolling",
    name: "Dog Rolling on Its Back",
    short: "Rolling",
    category: "behavior",
    rarity: "uncommon",
    emoji: "🔄",
    hue: 100,
    tips: "On its back in the grass, wriggling.",
  },
  {
    slug: "dog_sitting_on_command",
    name: "Dog Doing a Trick",
    short: "Doing a Trick",
    category: "behavior",
    rarity: "uncommon",
    emoji: "🎩",
    hue: 280,
    tips: "Sit, shake, roll over, or any trick performed on cue.",
  },
  {
    slug: "dog_howling",
    name: "Dog Howling",
    short: "Howling",
    category: "behavior",
    rarity: "rare",
    emoji: "🌙",
    hue: 240,
    tips: "A sustained howl, not a bark.",
  },
  {
    slug: "dog_zoomies",
    name: "Dog with the Zoomies",
    short: "Zoomies",
    category: "behavior",
    rarity: "uncommon",
    emoji: "💨",
    hue: 170,
    tips: "Sudden frantic sprinting in circles for no reason.",
  },
  {
    slug: "dog_napping",
    name: "Dog Napping Outside",
    short: "Napping",
    category: "behavior",
    rarity: "common",
    emoji: "😴",
    hue: 250,
    tips: "Asleep in public: a patio, park, or shop doorway.",
  },

  // ---------- Clothing ----------
  {
    slug: "dog_wearing_clothing",
    name: "Dog Wearing Clothing",
    short: "Wearing Clothes",
    category: "clothing",
    rarity: "common",
    emoji: "🧥",
    hue: 330,
    tips: "Any sweater, jacket, or shirt (not a plain harness).",
  },
  {
    slug: "dog_wearing_bandana",
    name: "Dog Wearing a Bandana",
    short: "Bandana",
    category: "clothing",
    rarity: "common",
    emoji: "🧣",
    hue: 0,
    tips: "A scarf or bandana around the neck.",
  },
  {
    slug: "dog_wearing_raincoat",
    name: "Dog Wearing a Raincoat",
    short: "Raincoat",
    category: "clothing",
    rarity: "uncommon",
    emoji: "🌧️",
    hue: 55,
    tips: "A waterproof coat, hood optional.",
  },
  {
    slug: "dog_wearing_boots",
    name: "Dog Wearing Boots",
    short: "Boots",
    category: "clothing",
    rarity: "rare",
    emoji: "👢",
    hue: 20,
    tips: "Booties on at least two paws.",
  },
  {
    slug: "dog_wearing_sunglasses",
    name: "Dog Wearing Sunglasses or Hat",
    short: "Sunglasses/Hat",
    category: "clothing",
    rarity: "rare",
    emoji: "🕶️",
    hue: 45,
    tips: "Goggles, sunglasses, or a hat that stays on.",
  },
  {
    slug: "dog_light_up_collar",
    name: "Dog with a Light-Up Collar",
    short: "Glow Collar",
    category: "clothing",
    rarity: "uncommon",
    emoji: "💡",
    hue: 140,
    tips: "LED collar or clip-on light, lit.",
  },
  {
    slug: "dog_service_vest",
    name: "Dog Wearing a Working Vest",
    short: "Working Vest",
    category: "clothing",
    rarity: "uncommon",
    emoji: "🦺",
    hue: 30,
    tips: "Service, guide, or 'in training' vest. Do not distract the dog.",
  },

  // ---------- Owner interaction ----------
  {
    slug: "person_walking_two_dogs",
    name: "Person Walking Two Dogs",
    short: "Two Dogs, One Walker",
    category: "owner_interaction",
    rarity: "common",
    emoji: "2️⃣",
    hue: 150,
    tips: "One person, exactly two dogs on leash.",
  },
  {
    slug: "person_walking_three_dogs",
    name: "Person Walking Three or More Dogs",
    short: "Three+ Dogs",
    category: "owner_interaction",
    rarity: "uncommon",
    emoji: "3️⃣",
    hue: 160,
    tips: "One person with three or more dogs at once.",
  },
  {
    slug: "dog_in_stroller",
    name: "Dog Riding in a Stroller",
    short: "In a Stroller",
    category: "owner_interaction",
    rarity: "uncommon",
    emoji: "👶",
    hue: 310,
    tips: "A dog (not a baby) in a stroller or pet pram.",
  },
  {
    slug: "dog_in_backpack",
    name: "Dog Riding in a Backpack or Bag",
    short: "In a Bag",
    category: "owner_interaction",
    rarity: "uncommon",
    emoji: "🎒",
    hue: 270,
    tips: "Carried in a backpack, tote, or front carrier.",
  },
  {
    slug: "dog_in_bike_basket",
    name: "Dog in a Bike Basket or Trailer",
    short: "Bike Basket",
    category: "owner_interaction",
    rarity: "rare",
    emoji: "🚲",
    hue: 190,
    tips: "Riding along on a bicycle or in a bike trailer.",
  },
  {
    slug: "dog_being_carried",
    name: "Dog Being Carried",
    short: "Carried",
    category: "owner_interaction",
    rarity: "common",
    emoji: "🤱",
    hue: 350,
    tips: "Held in someone's arms.",
  },
  {
    slug: "dog_getting_treat",
    name: "Dog Getting a Treat",
    short: "Treat Time",
    category: "owner_interaction",
    rarity: "common",
    emoji: "🦴",
    hue: 40,
    tips: "Being hand-fed a treat.",
  },
  {
    slug: "dog_tied_outside_shop",
    name: "Dog Waiting Outside a Shop",
    short: "Waiting Outside",
    category: "owner_interaction",
    rarity: "common",
    emoji: "🏪",
    hue: 200,
    tips: "Leashed and waiting patiently outside a store or cafe.",
  },
  {
    slug: "dog_off_leash",
    name: "Off-Leash Dog",
    short: "Off Leash",
    category: "owner_interaction",
    rarity: "common",
    emoji: "🏃",
    hue: 110,
    tips: "Walking without a leash (in a legal area).",
  },
  {
    slug: "matching_outfits",
    name: "Dog & Owner in Matching Outfits",
    short: "Matching Outfits",
    category: "owner_interaction",
    rarity: "rare",
    emoji: "👯",
    hue: 290,
    tips: "Clearly coordinated colors or patterns.",
  },

  // ---------- Environment ----------
  {
    slug: "dog_in_car_window",
    name: "Dog with Head Out a Car Window",
    short: "Car Window",
    category: "environment",
    rarity: "uncommon",
    emoji: "🚗",
    hue: 205,
    tips: "Head out the window, ears flapping.",
  },
  {
    slug: "dog_on_patio",
    name: "Dog at a Cafe Patio",
    short: "Cafe Dog",
    category: "environment",
    rarity: "common",
    emoji: "☕",
    hue: 25,
    tips: "Sitting with people at an outdoor cafe or restaurant.",
  },
  {
    slug: "dog_in_water_bowl",
    name: "Dog Drinking from a Public Bowl",
    short: "Public Bowl",
    category: "environment",
    rarity: "common",
    emoji: "🥣",
    hue: 195,
    tips: "Drinking from a bowl left outside a shop or in a park.",
  },
  {
    slug: "dog_in_fountain",
    name: "Dog in a Fountain or Puddle",
    short: "Puddle Dog",
    category: "environment",
    rarity: "uncommon",
    emoji: "⛲",
    hue: 185,
    tips: "Standing or splashing in a fountain, puddle, or splash pad.",
  },
  {
    slug: "dog_on_balcony",
    name: "Dog Watching from a Window or Balcony",
    short: "Window Watcher",
    category: "environment",
    rarity: "common",
    emoji: "🪟",
    hue: 230,
    tips: "Looking out from inside a home or from a balcony.",
  },
  {
    slug: "dog_on_transit",
    name: "Dog on a Bus or Train",
    short: "Transit Dog",
    category: "environment",
    rarity: "rare",
    emoji: "🚌",
    hue: 215,
    tips: "Riding public transit.",
  },

  // ---------- Special ----------
  {
    slug: "puppy",
    name: "Puppy",
    category: "special",
    rarity: "common",
    emoji: "🐾",
    hue: 45,
    tips: "Clearly a puppy: oversized paws, soft features, wobbly gait.",
  },
  {
    slug: "senior_dog",
    name: "Senior Dog",
    short: "Grey Muzzle",
    category: "special",
    rarity: "common",
    emoji: "👴",
    hue: 0,
    tips: "Grey muzzle, slow walk, dignified.",
  },
  {
    slug: "very_large_dog",
    name: "Very Large Dog",
    short: "Very Large",
    category: "special",
    rarity: "uncommon",
    emoji: "🐘",
    hue: 210,
    tips: "Hip height at or above a person's waist.",
  },
  {
    slug: "very_small_dog",
    name: "Very Small Dog",
    short: "Very Small",
    category: "special",
    rarity: "common",
    emoji: "🐁",
    hue: 60,
    tips: "Could fit in a handbag.",
  },
  {
    slug: "three_legged_dog",
    name: "Three-Legged Dog",
    short: "Tripawd",
    category: "special",
    rarity: "rare",
    emoji: "🦿",
    hue: 130,
    tips: "Three legs, still happy.",
  },
  {
    slug: "dog_with_cone",
    name: "Dog Wearing a Cone",
    short: "Cone of Shame",
    category: "special",
    rarity: "rare",
    emoji: "📢",
    hue: 55,
    tips: "Wearing a recovery cone or donut collar.",
  },
  {
    slug: "fluffiest_dog",
    name: "Extremely Fluffy Dog",
    short: "Extremely Fluffy",
    category: "special",
    rarity: "uncommon",
    emoji: "☁️",
    hue: 200,
    tips: "Coat so thick the body shape is a mystery (Samoyed, Chow, Pomeranian, etc.).",
  },
];

export const DOG_TILES: Tile[] = SEEDS.map((s, i) => ({
  id: `dog_${s.slug}`,
  themeId: THEME_ID,
  slug: s.slug,
  name: s.name,
  shortName: s.short,
  category: s.category,
  rarityScore: rarityScoreFor(s.rarity),
  rarityCategory: s.rarity,
  description: s.description,
  identificationTips: s.tips,
  sizeNotes: s.size,
  coatNotes: s.coat,
  primaryImage: {
    id: `img_${s.slug}`,
    imageType: "primary",
    url: `/tiles/${s.slug}_lg.webp`,
    thumbnailUrl: `/tiles/${s.slug}.webp`,
    altText: `Illustration of ${s.name}`,
    approved: true,
    displayOrder: 0,
  },
  active: true,
  sortOrder: i,
  metadata: { placeholder: { emoji: s.emoji, hue: s.hue } },
}));

export const DOG_THEME: Theme = {
  id: THEME_ID,
  slug: "dog",
  name: "Dog Spotting",
  description: "Spot breeds, behaviors, and outfits on real dogs around you.",
  status: "published",
  defaultGameMode: "full_card",
  defaultCardColumns: 4,
  defaultCardRows: 4,
  recommendedAge: "All ages",
  fullCardLabel: "Full Card",
  config: {
    freeCenter: false,
    defaultRespins: 3,
    rarityQuota: { common: 8, uncommon: 5, rare: 3 },
    categoryRules: [
      { category: "breed", max: 10 },
      { category: "clothing", max: 2 },
    ],
  },
  tiles: DOG_TILES,
};
